### Register
POST http://127.0.0.1:3001/api/auth/register
Content-Type: application/json

{
  "name": "gabrielalberini",
  "age": 29,
  "email": "gabialberini1@gmail.com",
  "password": "123prueba",
  "role": "admin"
}

### Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "gabialberini1@gmail.com",
  "password": "123prueba"
}