### Storages
GET http://127.0.0.1:3001/api/storages

### Storage
GET http://127.0.0.1:3001/api/storages/1

### Post file
### En Postman para poder enviar achivos

### Delete storage
DELETE  http://127.0.0.1:3001/api/storages/6639317c1349f79fbf84dc51