### Tracks
GET http://127.0.0.1:3001/api/tracks/?page=3

### Track
GET http://127.0.0.1:3001/api/tracks/661a864356647c4641535cf7

### Create track
POST http://127.0.0.1:3001/api/tracks
Content-Type: application/json

{
  "name": "Otra nueva cancion",
  "album": "Nombre del Álbum",
  "cover": "URL de la Portada",
  "artist": {
    "name": "Nombre del Artista",
    "nickname": "Apodo del Artista",
    "nationality": "Nacionalidad del Artista"
  },
  "duration": {
    "start": 0,
    "end": 180
  },
  "mediaId": "6074e105ac83c317d0c2fd2a" 
}


### Update track
PATCH http://127.0.0.1:3001/api/tracks/6619aeb2194dc754ca63a9ba
Content-Type: application/json

{
  "name": "Canción de ejemplo",
  "artist": {
    "name": "Artista de ejemplo"
  }
}

### Delete tracks
DELETE  http://127.0.0.1:3001/api/tracks/6619aeb2194dc754ca63a9ba
