### Tracks
GET http://127.0.0.1:3001/api/tracks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNlNzE3YTQ3N2I3M2VmMzZhODI4MmEiLCJyb2xlIjpbImFkbWluIl0sImlhdCI6MTcxNTM3Mjc1MCwiZXhwIjoxNzE1Mzc5OTUwfQ.gA7rWFtZ2YKwTcp5ZxwaXY4ffxdbsqqEsyae2GmuX2I

### Track
GET http://127.0.0.1:3001/api/tracks/661aa8d64ccc5993f067b046

### Create track
POST http://127.0.0.1:3001/api/tracks
Content-Type: application/json

{
  "name": "Otra nueva cancion",
  "album": "Nombre del Álbum",
  "cover": "URL de la Portada",
  "artist": {
    "name": "Nombre del Artista",
    "nickname": "Apodo del Artista",
    "nationality": "Nacionalidad del Artista"
  },
  "duration": {
    "start": 0,
    "end": 180
  },
  "mediaId": "6074e105ac83c317d0c2fd2a" 
}


### Update track
PATCH http://127.0.0.1:3001/api/tracks/663d0f8aa6b758af3f95b094
Content-Type: application/json

{
  "name": "Canción de ejemplo",
  "artist": {
    "name": "Artista de ejemplo"
  }
}

### Delete tracks
DELETE  http://127.0.0.1:3001/api/tracks/663d0f8aa6b758af3f95b094
